version: '3.4'

services:
  libadore:
    image: libadore:latest
    container_name: libadore
    hostname: libadore
    depends_on:
      - libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore
      args:
        PROJECT: libadore

  libadore_build:
    image: libadore_build:latest
    container_name: libadore_build
    hostname: libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore.build
      args:
        PROJECT: libadore
        CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH:-}
  libadore_test:
    image: libadore_test:latest
    container_name: libadore_test
    hostname: libadore_test
    depends_on:
      - libadore_build
    build:
      context: .
      network: host
      dockerfile: Dockerfile.libadore.test
      args:
        PROJECT: libadore
    entrypoint: sh -c 'cd build && ctest 2>&1'
